export enum ExtendedHttpStatus {
    REQ_BODY_VALIDATION_ERROR = 400001,
    INVALID_SIGN_IN_CREDENTIALS,
    USER_CREATING_ERROR,
    USER_SESSION_CREATING_ERROR,

    REQ_BODY_MALFORMED = 403001,
    TOKEN_MALFORMED,
    TOKEN_EXPIRED,
    USER_MANAGEMENT_ERROR,

    USER_NOT_FOUND = 404001,
    USER_SESSION_NOT_FOUND,

    UNKNOWN_ERROR = 500001,
}
